version: '2'
services:
  nats-server :
    image: nats:latest
    container_name: nats-server
    networks:
      - nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
networks:
  nats: